### ISSUE TITLE
some src files seem to be missing, it does not compile out of the box

### ISSUE THREAD

**Issue by meinds** [lighthouse3d/VSL#1]
Ill tried to compile this using VS2013.
It seems that the following files are lacking:
    include\vsGLInfoLib.h
    include\vslibs.h
    include\vsResModelLib.h
    source\vsResModelLib.cpp
If these should actually be added or remove from the project files I do not know.

I see the following type of compile errors:
1>c1xx : fatal error C1083: Cannot open source file: 'source\vsResModelLib.cpp': No such file or directory
1>d:\views\vslgit_vs2012\trunk\vsl\source\vsglinfolib.cpp(19): fatal error C1083: Cannot open include file: 'vsGLInfoLib.h': No such file or directory

**Comment by lighthouse3d** [comment]
These are fixed now with the CMake project. 

Regards,

António

**Comment by meinds** [comment]
Thanks for these fixes!
It now compiles and runs out of the box, provided that the build directory to be filled by CMake is chosen to be on the same level as the VSL directory.

**Comment by lighthouse3d** [comment]
Thanks for the feedback. I'll try to make it more generic soon.

Best regards,

António

**Comment by lighthouse3d** [comment]
OK, got it (I hope). Thanks again.

António
