### ISSUE TITLE
Getting linker warnings related to compiling against static glew library.

### ISSUE THREAD

**Issue by meinds** [lighthouse3d/VSL#2]
Hi Guys,

I was playing around with these VSL libraries again after some time, and I noticed warning messages related to compiling against the glew static library.

Every time I link my application against vsl.lib or vsld.lib I get the below set of warnings (which is unhandy since in obfuscate the warnings I do want to see.

It cost me some time to find, but at the end the fix is simple. The define GLEW_STATIC needs to be defined before any of the lines with "#include <GL/glew.h>" in the VSL source files is performed. (This is also true for an application that also uses the same glew). I tested this by adding this define as a preprocessor define in the VSL project settings of MSVC (I use VS2013).

In case the case of the CMAKE flow I expect you can simply add the line:
add_definitions(-DGLEW_STATIC)
to CMakeLists.txt in the VSL directory.

I though I let you know, then if you add it, others can also benefit.

Cheers,
Koen

1>vsld.lib(vsMathLib.obj) : warning LNK4049: locally defined symbol ___glewGetUniformLocation imported
1>vsld.lib(vsShaderLib.obj) : warning LNK4049: locally defined symbol ___glewGetUniformLocation imported
1>vsld.lib(vsGLInfoLib.obj) : warning LNK4049: locally defined symbol ___glewGetUniformLocation imported
1>vsld.lib(vsMathLib.obj) : warning LNK4049: locally defined symbol ___glewProgramUniformMatrix3fv imported
1>vsld.lib(vsShaderLib.obj) : warning LNK4049: locally defined symbol ___glewProgramUniformMatrix3fv imported
1>vsld.lib(vsMathLib.obj) : warning LNK4049: locally defined symbol ___glewProgramUniformMatrix4fv imported
1>vsld.lib(vsShaderLib.obj) : warning LNK4049: locally defined symbol ___glewProgramUniformMatrix4fv imported
1>vsld.lib(vsFontLib.obj) : warning LNK4049: locally defined symbol ___glewBindBuffer imported
1>vsld.lib(vsShaderLib.obj) : warning LNK4049: locally defined symbol ___glewBindBuffer imported
1>vsld.lib(vsResourceLib.obj) : warning LNK4049: locally defined symbol ___glewBindBuffer imported
1>vsld.lib(vsModelLib.obj) : warning LNK4217: locally defined symbol ___glewBindBuffer imported in function __unwindfunclet ...

**Comment by lighthouse3d** [comment]
Hi Koen,

Yes, those were annoying. Fixed, many thanks.

Best Regards,

António
