### ISSUE TITLE
Moving call to vsfl.prepareSentence() to program setup gives unexpected effects

### ISSUE THREAD

**Issue by meinds** [lighthouse3d/VSL#3]
In my GLUT program I use VSFL for drawing text as an overlay on the screen.
Here follows a explanation of a bug I could not pinpoint and fix myself.

In my renderScene() callback function (set using glutDisplayFunc(renderScene);) I use multiple lines such as the following to display an overlay of text:
vsfl.renderSentence(10, 30, helpSentence1);

This works fine when the line:
vsfl.prepareSentence(helpSentence1, "Bla bla");
that initializes the underlaying vertex-array-object is placed "close enough" to the above vsfl.renderSentence.
Since the text from helpSentence1 is static, I thought I move the "prepareSentence" part to the setup of the program where it is done only once.

However then a crash appears. Zooming in on the issue I noticed that the crash depends on the location of the prepareSentence() call in the code w.r.t. the following lines of GL setup code (note that these lines assume the availability of  OpenGL COMPATIBILITY_PROFILE mode. I use opengl API v3.3 on NVidia GTX950M)

    1) glEnableClientState(GL_VERTEX_ARRAY);
    2) glEnableClientState(GL_TEXTURE_COORD_ARRAY);
    3) glVertexPointer(4, GL_FLOAT, 0, modelCoord);
    4) glTexCoordPointer(2, GL_FLOAT, 0, textureCoord);

When the renderSentence() call is placed before line 3) there is the crash (without any meaning full info, as to hint on what went wrong). When it is placed after line 4, everything is fine. When placed inbetween line 3) and 4) there is no crash but the texture associated to "textureCoord" is completely deformed.

Zooming in more, it turns out that when I comment out the following line:
glBindVertexArray(vao);
in VSFontLib::prepareSentence() and recompile the VSL library (debug mode), and still having the renderSentence() call just before line 4), the texture is correctly shown (but of course the texture overly is not shown anymore)

In my renderScene code glDrawElements() is used to draw the texture, based on the vertex array (one-time only) setup by the above glVertexPointer() and glTexCoordPointer() calls. I also understand that the vertex array object created in prepareSentence() can also drive a same glDrawElements() call. However the call to glBindVertexArray(0) in the end of prepareSentence() should nullify it's effects of accidental further use, right?
However it seems that somehow the vertex array mechanisms of glVertexPointer() and glTexCoordPointer() seem to still somehow be influenced.

I'm puzzled. To me this seems like a vsfl bug, and that is why I submit this issue. But I might be mistaken, and it might be some use (of not combinable APIs?) which is out of the (compatibility profile) spec?

Perhaps, you can share a light on this, and mention if moving the vsfl.prepareSentence call to a one-time only setup, should work in the first place?

Thanks.

**Comment by lighthouse3d** [comment]
Hi Koen,

I've managed to use prepareSentence right after initVSL with a fixed sentence, and it renders OK. Can you provide me with an example where it fails so that I can look further into it?

Best Regards,

António

**Comment by meinds** [comment]
Hi António,

Good to hear that you are picking this up!
I will provide you with an example later today or later in this week.

Regards,
Koen

2017-10-02 0:08 GMT+02:00 Lighthouse3D <notifications@github.com>:

**Comment by meinds** [comment]
hI António,

See the attached .cpp file:
line 758:  makes a call to createVsflHelpScentences() containing several
calls to vsfl.prepareSentence() with a fixed string.

That works fine.

moving the call a bit earlier, to line 748, may give a deformed texture,
but just now it crashed.

I hope you can reproduce it.

Thanks for looking into it!

Cheers,
Koen

2017-10-02 0:08 GMT+02:00 Lighthouse3D <notifications@github.com>:

**Comment by lighthouse3d** [comment]
Hi Koen, 
The attachment is missing :-(
Can you send it again?

Best Regards,

António

**Comment by meinds** [comment]
Hi António,

That is strange since, in the sent email in my outbox the attachment is
there.
Here it is again. Now with .zip extention renamed to ._z_.
Hope it works now.

Regards,
Koen

2017-10-02 23:37 GMT+02:00 Lighthouse3D <notifications@github.com>:

**Comment by lighthouse3d** [comment]
Hi Koen,

I don't know why but I'm not getting any attachment, not in my mail, and not in the issues page. Can you share the cpp via dropbox or any other cloud service?

Best Regards,

António

**Comment by meinds** [comment]
Hi António,

It seems that attachments do not work via this "github email channel".

I've put the file on my dropbox. You should be able to get it via this link:
https://www.dropbox.com/s/dcxlq76whj5gzg3/src_for_prepareSentence_problem.zip?dl=0
Let me know if it does not work.

Best regards,
Koen


2017-10-04 1:59 GMT+02:00 Lighthouse3D <notifications@github.com>:

**Comment by lighthouse3d** [comment]
Hi Koen,

I think I have an explanation for what is going on. I believe that the main issue is that function prepareSentence uses the new GL notation, i.e. glVertexAttribPointer, and in the code you supplied prepareSentence is preceded by glVertexPointer and afterwards we have a glTexCoordPointer. What prepareSentence does, besides preparing the buffers is define the semantics for the buffers, but it gets a glTexCoordPointer immediately after, which may (well, it actually does) ruin the prepareSentence setup.

Hope this helps,

António

**Comment by meinds** [comment]
Hi António,

Thank you for your explanation. It sound understandable.It indeed helps!

I'll try to rephrase with my own words (to check if I get it):
This does than mean that if calls like glVertexPointer and/or
glTexCoordPointer are given before glVertexAttribPointer (within
prepareScentence) and the rendering of it (in glDrawElements) after it
things go wrong, since apparently glVertexPointer + glTexCoordPointer use
same underlaying buffers as glVertexAttribPointer .
So this would mean that glVertexPointer and/or glTexCoordPointer can not be
used "mixed" with glVertexAttribPointer (and thus prepareScentence); other
than to have no prepareScentence inbetween the associated glDrawElements...

Perhaps this might be a limitation that could be documented at the
prepareScentence method?

Thanks,
Koen

2017-10-05 1:13 GMT+02:00 Lighthouse3D <notifications@github.com>:

**Comment by lighthouse3d** [comment]
Hi Koen,

Your description sounds good. 

This issue it is not particular to the prepareSentence method. There are tons of things that will most likely not work if mixing fixed and shader based functionality. To be honest I was surprised to see that you managed to get it working in this dual scenario. VSL is designed to work with shaders only.

Thanks for the feedback,

António
